### ISSUE TITLE
User Guide

### ISSUE THREAD

**Issue by hendisantika** [FaztWeb/angular7-mysql-crud#1]
Nice repo.
Is there any user guide or blog post about how to create this app from the beginning?

How to run the server app?
Is it nodeJS app (server)?

Thanks

**Comment by fazt** [comment]
> Nice repo.
> Is there any user guide or blog post about how to create this app from the beginning?
> 
> How to run the server app?
> Is it nodeJS app (server)?
> 
> Thanks

Hello @hendisantika I'm creating it just right now, probably you can watch it in two days in my youtube channel https://www.youtube.com/fazttech
Thanks :)

**Comment by hendisantika** [comment]
Ooo... Ya ya ya.
OK then.
Thanks

**Comment by fazt** [comment]
@hendisantika This is the link to the tutorial -> Link to video: https://youtu.be/lxYB79ANJM8
Good luck! :+1:

**Comment by hendisantika** [comment]
Nice.
Thank You @FaztTech

**Comment by FaztTech** [comment]
resolved
